name: EndlessCoinflip
version: 0.0.8
main: dev.itsnotskyex.EndlessCoinflip
api-version: '1.21'
author: ItsNotSkye
description: A feature-rich Coinflip plugin for Minecraft servers.
depend: [Vault]

commands:
  coinflip:
    description: Open the Coinflip menu or create a match
    aliases: [cf]
    usage: /coinflip [wager|player <wager>|accept|deny|bot <wager>|cancel|stats|history|top <page>|help|reload]

permissions:
  endlesscoinflip.use:
    description: Allows use of all coinflip commands
    default: true
  endlesscoinflip.admin:
    description: Allows use of admin commands (reload)
    default: op